apiVersion: skaffold/v2beta26
kind: Config
metadata:
  name: kevo
build:
  artifacts:
  - image: quay.io/hown3d/kevo
    docker:
      dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
    - deploy/kube.yaml
