apiVersion: skaffold/v2beta26
kind: Config
metadata:
  name: kevo
build:
  artifacts:
  - image: quay.io/hown3d/kevo/kubernetes-fetcher
    docker:
      dockerfile: deploy/fetcher/kubernetes/Dockerfile
  - image: quay.io/hown3d/kevo/api
    docker:
      dockerfile: deploy/api/Dockerfile
  local:
    useBuildkit: true
deploy:
  helm:
    releases:
      - name: kevo
        chartPath: deploy/kevo
        artifactOverrides:
          api: quay.io/hown3d/kevo/api # no tag present!
          kubernetes: quay.io/hown3d/kevo/kubernetes-fetcher # no tag present!
        imageStrategy:
          helm: {}
  
