apiVersion: apps/v1
kind: Deployment
metadata:
  name: kevo-kubernetes-fetcher-deployment
spec:
  selector:
    matchLabels:
      app: kevo-kubernetes-fetcher
  template:
    metadata:
      labels:
        app: kevo-kubernetes-fetcher
    spec:
      serviceAccount: kevo-kubernetes-fetcher
      containers:
      - name: kevo-kubernetes-fetcher
        image: "{{.Values.kubernetes.repository}}:{{.Values.kubernetes.tag}}"
        env:
          - name: KEVO_SERVER_ADDRESS
            value: "kevo-api:10000"
        resources:
          requests:
            memory: "32Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kevo-kubernetes-fetcher

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  # "namespace" omitted since ClusterRoles are not namespaced
  name: kevo-pod-reader
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list"]

---

apiVersion: rbac.authorization.k8s.io/v1
# This cluster role binding allows anyone in the "manager" group to read secrets in any namespace.
kind: ClusterRoleBinding
metadata:
  name: kevo-pod-reader
subjects:
- kind: ServiceAccount
  name: kevo-kubernetes-fetcher 
  namespace: default
roleRef:
  kind: ClusterRole
  name: kevo-pod-reader
  apiGroup: rbac.authorization.k8s.io