apiVersion: apps/v1
kind: Deployment
metadata:
  name: trivy-server
spec:
  selector:
    matchLabels:
      app: trivy-server
  replicas: 5
  template:
    metadata:
      labels:
        app: trivy-server
    spec:
      containers:
      - name: trivy-server
        image: bitnami/trivy:0.22.0
        args:
          - "--debug"
          - "server"
          - "--listen=0.0.0.0:4954"
          - "--cache-backend=redis://kevo-redis-headless:6379"
        resources:
          limits:
            memory: "100Mi"
            cpu: "250m"
          requests:
            memory: "50Mi"
            cpu: "100m"
        ports:
        - containerPort: 4954
          name: trivy
        volumeMounts:
          - mountPath: /.cache/trivy
            name: cache
      volumes:
        - name: cache
          emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: trivy-server
spec:
  selector:
    app: trivy-server
  ports:
  - port: 4954
    targetPort: trivy
