// Code generated by mockery v2.10.0. DO NOT EDIT.

package mocks

import (
	context "context"

	ecs "github.com/aws/aws-sdk-go-v2/service/ecs"

	mock "github.com/stretchr/testify/mock"
)

// ECSAPI is an autogenerated mock type for the ECSAPI type
type ECSAPI struct {
	mock.Mock
}

// DescribeTaskDefinition provides a mock function with given fields: ctx, input, optFns
func (_m *ECSAPI) DescribeTaskDefinition(ctx context.Context, input *ecs.DescribeTaskDefinitionInput, optFns ...func(*ecs.Options)) (*ecs.DescribeTaskDefinitionOutput, error) {
	_va := make([]interface{}, len(optFns))
	for _i := range optFns {
		_va[_i] = optFns[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, input)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *ecs.DescribeTaskDefinitionOutput
	if rf, ok := ret.Get(0).(func(context.Context, *ecs.DescribeTaskDefinitionInput, ...func(*ecs.Options)) *ecs.DescribeTaskDefinitionOutput); ok {
		r0 = rf(ctx, input, optFns...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ecs.DescribeTaskDefinitionOutput)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *ecs.DescribeTaskDefinitionInput, ...func(*ecs.Options)) error); ok {
		r1 = rf(ctx, input, optFns...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
